### ISSUE TITLE
Does not build on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by m-mueller678** [cloudius-systems/osv#1331]
The most recent commit on the master branch does not build for me.
```bash
git clone git@github.com:cloudius-systems/osv.git osv_build_issue
cd osv_build_issue/
git submodule update --init --recursive
./scripts/build image=cli
```
Fails with
```
core/net_trace.cc:82:29: error: redeclaration ‘constexpr typename std::iterator_traits< <template-parameter-1-1> >::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = mbuf_iterator; typename std::iterator_traits< <template-parameter-1-1> >::difference_type = long unsigned int]’ differs in ‘constexpr’ from previous declaration
   82 |     friend constexpr size_t std::distance<mbuf_iterator>(mbuf_iterator, mbuf_iterator);
      |                             ^~~
In file included from /usr/include/c++/11/bits/stl_algobase.h:66,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/ios:40,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from include/osv/trace.hh:11,
                 from core/net_trace.cc:8:
/usr/include/c++/11/bits/stl_iterator_base_funcs.h:138:5: note: previous declaration ‘typename std::iterator_traits< <template-parameter-1-1> >::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = mbuf_iterator; typename std::iterator_traits< <template-parameter-1-1> >::difference_type = long unsigned int]’
  138 |     distance(_InputIterator __first, _InputIterator __last)
      |     ^~~~~~~~
core/net_trace.cc: In function ‘typename std::iterator_traits< <template-parameter-1-1> >::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = mbuf_iterator; typename std::iterator_traits< <template-parameter-1-1> >::difference_type = long unsigned int]’:
core/net_trace.cc:90:15: error: ‘mbuf* mbuf_iterator::_m’ is private within this context
   90 |     if (first._m == second._m) {
      |               ^~
```
I am using `g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`.

The previous commit (ba39c4c08eda4cde5bf29bba98b45d918b046f36) gets past this step.
It later freezes on installing luasocket, but I vaguely recall having that issue in osv earlier this year.

**Comment by m-mueller678** [comment]
Tested with `./scripts/build image=rogue` to avoid lua. This builds fine on the previous commit, but has the same error on the most recent.

As a side note, the wiki uses image=cli as an example when showing the build process. I have therefore used that to test my setup when picking up osv. Changing it to something without Lua would make sense, given the troubles it seems to cause with this and openssl.

**Comment by wkozaczuk** [comment]
I agree with your suggestion to change the default image. Maybe `httpserver-api` would be a better choice.
