### ISSUE TITLE
lua package requires openssl 1.0

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1022]
As explained in commit af16f934ab795e607e3041dc707dbcd7ea4a7229, our modules/lua package (used by, for example, the "cli" package), takes a specific old version of luasec, which only works for OpenSSL 1.0.
This required bizarre workarounds for modern Linux distributions, which already have OpenSSL 1.1 which doesn't work on that old luasec version.  For example for Fedora 26 and above we install "compat-openssl10-devel" which replaces openssl by the 1.0 version (see commit af16f934ab795e607e3041dc707dbcd7ea4a7229). Arch Linux also has a similar package (see commmit 64e14440624998d0ebf2f04bee9a8fa3cc9db757). The last comment in issue #899 is about needing a similar package for Ubuntu.

But while we could do that (i.e., also specify which package we need for Ubuntu, hoping there is one) as a quick short-term solution, the better long-term solution is to update Lua in modules/lua to a more modern version that works on modern distributions with modern OpenSSL versions.

**Comment by nyh** [comment]
This issue is starting to annoy me, as other software starts to crop up which doesn't build with the antique openssl 1.0 so I don't want it on my build system.

I tried upgrading modules/lua/Makefile to take Lua 5.2.4 instead of 5.2.3, but it still only works with OpenSSL 1.0. When I tried to just choose the latest version (5.3.5), unfortunately the current Makefile doesn't work, and it will obviously need some work to fix it.

**Comment by wkozaczuk** [comment]
I am in the process of updating lua module to use artifacts from host (lualib.so) so hopefully should have something that works with latest openSSL. It also needs updating other modules.

**Comment by kayhaw** [comment]
For Debian9, Ubuntu18.04/18.10, change the package by
```
# remove the default 1.1 version
sudo apt remove libssl-dev
# install the 1.0 version
sudo apt install libssl1.0-dev
```
If `libssl1.0-dev` can not be found by `apt` after removing `libssl-dev`, download `libssl1.0-dev` package from [here](https://pkgs.org/download/libssl1.0-dev) and install it by `sudo dpkg -i libssl1.0-dev_xxx.deb`

**BY THE WAY**, there seems to be a typo in `include/osv/sched.hh` at the **`master`** branch :sweat_smile: :
```
In file included from ../../include/osv/app.hh:15:0,                                      
                 from global_server.cc:11:                                                
../../include/osv/sched.hh: In member function ‘sched::thread::attr& sched::thread::attr::
name(std::__cxx11::string)’:                                                              
../../include/osv/sched.hh:362:13: error: ‘strlcpy’ was not declared in this scope        
             strlcpy(_name.data(), n.data(), sizeof(_name));                              
             ^~~~~~~                                                                      
../../include/osv/sched.hh:362:13: note: suggested alternative: ‘strncpy’                 
             strlcpy(_name.data(), n.data(), sizeof(_name));                              
             ^~~~~~~                                                                      
             strncpy                                                                      
  CXX obj/plain_server.o                                                                  
  CXX obj/request_handler.o                                                               
  CXX obj/json/formatter.o                                                                
```
Finally OSv is built and runs successfully :smile: [Works On Ubuntu18.04]
```
OSv v0.53.0-30-gc1b8059b            
eth0: 192.168.122.15                
Booted up in 592.94 ms              
Rest API server running on port 8000
/#                                  
```

**Comment by nyh** [comment]
"strlcpy" is not a typo, it's a safer replacement for strncpy, which exists in BSD, but never adopted to Linux (https://lwn.net/Articles/507319/), we also have it in OSv, and can use it.
I think we may be missing a #inlcude in sched.hh for strlcpy. I'll fix it.

**Comment by kayhaw** [comment]
> "strlcpy" is not a typo, it's a safer replacement for strncpy, which exists in BSD, but never adopted to Linux (https://lwn.net/Articles/507319/), we also have it in OSv, and can use it.
> I think we may be missing a #inlcude in sched.hh for strlcpy. I'll fix it.

Got it :ok_hand: , thanks for the explanation

**Comment by Pusnow** [comment]
In Linux, `strlcpy` is declared in `bsd/string.h`.

https://linux.die.net/man/3/strlcpy

I think it should use a macro to include the string header.

**Comment by nyh** [comment]
In my Linux (Fedora 29), there is no "bsd/string.h". In any case, sched.hh is an OSv-specific header file, it doesn't need to work with Linux header files. And we're really digressing from the issue that we need to update Lua, so it won't require OpenSSL 1.0...

**Comment by wkozaczuk** [comment]
@kayhaw @Pusnow the "strlcpy'" compilation issues got fixed with one this commit - https://github.com/cloudius-systems/osv/commit/7eda847a12dd2d89ea4ce516544a063635abf040. 
I am also working on upgrading both lua and httpserver to use openssl 1. Hopefully it will be ready soon.
