### ISSUE TITLE
centos 7 boost libs too old, 'tlsv12’ is not a member of ‘boost::asio::ssl::context’

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#746]
Compile error on Centos 7.2 VM.
```
git clone https://github.com/cloudius-systems/osv  # at 714cfd97e48ba5fe
cd osv
git submodule update --init --recursive
./scripts/build mode=debug image=cli -j8
...
ssl_server.cc: In function ‘boost::asio::ssl::context http::server::make_ssl_context(const string&, const string&, const string&)’:
ssl_server.cc:116:22: error: ‘tlsv12’ is not a member of ‘boost::asio::ssl::context’
     ssl::context ctx(ssl::context::tlsv12);
```
So centos 7.2 has too old boost libs for tlsv12.

Reverting f64563a97e9e8a4 helps. After revert and one compile, I can un-revert f64563a97e9e8a4, an image will compile (until first ```scripts/build mode=debug clean``` only?).

**Comment by justinc1** [comment]
I also get second error:
```
./scripts/build mode=debug image=cli -j8
...
  LINK libhttpserver.so
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/xlab/osv/modules/httpserver/osv-gui'
/usr/bin/ld: cannot find -ltools
```

Do I need to do?:
```
make mode=debug  -j8
./scripts/build mode=debug  -j8
./scripts/build mode=debug image=cli -j8
```

**Comment by nyh** [comment]
What version of Boost does Centos 7.2 have?

**Comment by justinc1** [comment]
```
yum provides */context_base.hpp
boost-devel-1.53.0-25.el7.x86_64 : The Boost C++ headers and shared development libraries
Repo        : base
```

**Comment by nyh** [comment]
Boost 1.53 is a 3 year old antique, so it's not surprising it's missing some features, but we should try, whenever possible, to support also older distributions which keep the minimums mentioned in the README (namely, gcc 4.8 and above). So your first observation - about tlsv12 - is indeed a bug which should be fixed.
The use of tlsv12 was added in commit 3b7bf3187a3d08fcf9801103d8d0476d3ece4152 as a security precaution (to not allow older weaker variants of SSL), but this feature was indeed only added to Boost 3 years ago (see https://svn.boost.org/trac/boost/ticket/7609).

Somebody on the web suggest that it should be possible to go behind Boost's back and set some OpenSSL parameters directly (OpenSSL has supported TLS 1.2 since 2008):

```c++
#include <openssl/ssl.h>
long ssl_disallowed = SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2;
ssl_disallowed &= ~SSL_OP_NO_TLSv1_2;
SSL_CTX_set_options(ctx.native_handle(), ssl_disallowed);
```

I did not test this, can you please?

As for the second problem, are you using the latest master? This might be because of the new "stage1" target, which doesn't include (I think) libtools.so. If this is the problem, an easy workaround is to add
$(out)/tools/libtools.so to stage1_targets in the Makefile. Can you please check if that helps?
But if this is the problem, the real fix is to move the silly libtools.so from the core OSv makefile into  modules/libtools - which already exists, and modules/httpserver already requires it.

**Comment by nyh** [comment]
The second issue is separate, and I was able to reproduce it. I'll create a new bug for it.

**Comment by nyh** [comment]
I opened issue #748 for the second bug. Let's use this issue to discuss only the first bug (the tlsv12 thing).

**Comment by justinc1** [comment]
The proposed workaround compiles, but TLS1.0 and only TLS1.0 works. Tested with
```
IP=osv

curl -v --cacert cacert.pem --cert ./client.pem --key client.key https://$IP:8000/os/version --tlsv1
# ok

curl -v --cacert cacert.pem --cert ./client.pem --key client.key https://$IP:8000/os/version --tlsv1.2
* Closing connection 0
curl: (35) Peer using unsupported version of security protocol.
# VM - error and httpserver exits
httpserver failed: remote_endpoint: Socket not connected
program /libhttpserver.so returned 1
```

A 'debug-decorated' function I ended with (at the end I tried to remove default_workarounds). 
```
#include <openssl/ssl.h>
#define PRINTC(aa) { fprintf(stderr, "TTRT line:%d " #aa " 0x%08x\n", __LINE__, (unsigned int)(aa)); }
ssl::context make_ssl_context(const std::string& ca_cert_path,
    const std::string& cert_path, const std::string& key_path)
{
    fprintf(stderr, "TTRT make_ssl_context\n");
    ssl::context ctx(ssl::context::tlsv1);

    PRINTC(SSL_OP_NO_SSLv2);
    PRINTC(SSL_OP_NO_SSLv3);
    PRINTC(SSL_OP_NO_TLSv1);
    PRINTC(SSL_OP_NO_TLSv1_1);
    PRINTC(SSL_OP_NO_TLSv1_2);

    PRINTC(ssl::context::default_workarounds);
    PRINTC(ssl::context::no_sslv2);

    long ssl_disallowed = SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1 | SSL_OP_NO_TLSv1_2;
    ssl_disallowed &= ~SSL_OP_NO_TLSv1_2;
    PRINTC(ssl_disallowed);
    SSL_CTX_set_options(ctx.native_handle(), ssl_disallowed);
    PRINTC( SSL_CTX_get_options(ctx.native_handle()) );

    ctx.set_verify_mode(ssl::verify_peer | ssl::verify_fail_if_no_peer_cert);
    ctx.load_verify_file(ca_cert_path);

    // We must set the client CA name list, otherwise browsers will error out
    // on connection attempt.
    set_client_CA_list(ctx, ca_cert_path);

    PRINTC( SSL_CTX_get_options(ctx.native_handle()) );
    //ctx.set_options(ssl::context::default_workarounds | ssl::context::no_sslv2 | ssl_disallowed);
    PRINTC( SSL_CTX_get_options(ctx.native_handle()) );
    ctx.use_certificate_file(cert_path, ssl::context::pem);
    ctx.use_private_key_file(key_path, ssl::context::pem);

    unsigned char session_ctx_id[32];
    if (!RAND_bytes(session_ctx_id, sizeof(session_ctx_id))) {
        throw std::runtime_error("RAND_bytes() failed, err=" + std::to_string(ERR_get_error()));
    }
    ::SSL_CTX_set_session_id_context(ctx.native_handle(), session_ctx_id, sizeof(session_ctx_id));

    return ctx;
}
```

**Comment by nyh** [comment]
Another guess as to a working workaround:
Can we use `ssl::context ctx(ssl::context::sslv23)` (as before commit 3b7bf318) but also add to the set_options() line some ssl::context::no_tlsv1 etc?

If push comes to shove and we can't solve this any other way, I guess we can have an "#if" for the old Boost, and in that case use the code from before commit 3b7bf318.

**Comment by justinc1** [comment]
That works, thank you. My current code is below.

```
#include <openssl/ssl.h>
ssl::context make_ssl_context(const std::string& ca_cert_path,
    const std::string& cert_path, const std::string& key_path)
{
    ssl::context ctx(ssl::context::sslv23);

    long ssl_disallowed = SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1;
    SSL_CTX_set_options(ctx.native_handle(), ssl_disallowed);

    ctx.set_verify_mode(ssl::verify_peer | ssl::verify_fail_if_no_peer_cert);
    ctx.load_verify_file(ca_cert_path);

    // We must set the client CA name list, otherwise browsers will error out
    // on connection attempt.
    set_client_CA_list(ctx, ca_cert_path);

    ctx.set_options(ssl::context::default_workarounds | ssl::context::no_sslv2 | ssl_disallowed);
    ctx.use_certificate_file(cert_path, ssl::context::pem);
    ctx.use_private_key_file(key_path, ssl::context::pem);

    unsigned char session_ctx_id[32];
    if (!RAND_bytes(session_ctx_id, sizeof(session_ctx_id))) {
        throw std::runtime_error("RAND_bytes() failed, err=" + std::to_string(ERR_get_error()));
    }
    ::SSL_CTX_set_session_id_context(ctx.native_handle(), session_ctx_id, sizeof(session_ctx_id));

    return ctx;
}
```

**Comment by nyh** [comment]
Excellent. If you can please send a patch, I'll apply it.
